[build]
  base = "server"  # Temel dizin olarak server'i belirtin
  publish = ""  # Yayın dizini, server/dist olarak ayarlanabilir, yapılandırmanıza göre güncelleyin
  command = "npm run build"  # Build komutu olarak sunucu başlatma komutunu belirtin

[[redirects]]
  from = "/*"
  to = "/api"
  status = 200